// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
/*function toreador(){
	
}*/
//testJson = "{ "sdFirstBeatOffset": 0.0, "sdSongName": "Scarlet Fire", "sdNotes": -4.0, "sdBpm": 100.0 } "

//toreadorJson = "{ \"sdSongName\": \"Toreador\", \"sdNotes\": [ { \"noteType\": { \"tName\": \"DraftPunk\", \"sprite\": 1.0, \"spawnBeatOff\": -24.0, \"obj\": 12.0 }, \"noteTypeId\": 2.0, \"hasSpawned\": false, \"spawnBeatOff\": -24.0, \"row\": 4.0, \"beat\": 4.0 }, { \"noteType\": { \"tName\": \"DraftPunk\", \"sprite\": 1.0, \"spawnBeatOff\": -24.0, \"obj\": 12.0 }, \"noteTypeId\": 2.0, \"hasSpawned\": false, \"spawnBeatOff\": -24.0, \"row\": 2.0, \"beat\": 8.0 }, { \"noteType\": { \"tName\": \"DraftPunk\", \"sprite\": 1.0, \"spawnBeatOff\": -24.0, \"obj\": 12.0 }, \"noteTypeId\": 2.0, \"hasSpawned\": false, \"spawnBeatOff\": -24.0, \"row\": 6.0, \"beat\": 12.0 } ], \"sdBpm\": 108.0, \"sdFirstBeatOffset\": 0.0 } "
global.songJsons[SONG.scarletFire] = "{ \"sdSongName\": \"Scarlet Fire\", \"sdNotes\": [ { \"noteType\": { \"tName\": \"DraftPunk\", \"sprite\": 1.0, \"spawnBeatOff\": -24.0, \"obj\": 12.0 }, \"noteTypeId\": 2.0, \"hasSpawned\": false, \"spawnBeatOff\": -24.0, \"row\": 4.0, \"beat\": 4.0 }, { \"noteType\": { \"tName\": \"DraftPunk\", \"sprite\": 1.0, \"spawnBeatOff\": -24.0, \"obj\": 12.0 }, \"noteTypeId\": 2.0, \"hasSpawned\": false, \"spawnBeatOff\": -24.0, \"row\": 2.0, \"beat\": 8.0 }, { \"noteType\": { \"tName\": \"DraftPunk\", \"sprite\": 1.0, \"spawnBeatOff\": -24.0, \"obj\": 12.0 }, \"noteTypeId\": 2.0, \"hasSpawned\": false, \"spawnBeatOff\": -24.0, \"row\": 6.0, \"beat\": 12.0 } ], \"sdBpm\": 174.0, \"sdFirstBeatOffset\": 0.0 } "
global.songJsons[1] = "{ \"sdSongName\": \"Toreador\", \"sdNotes\": [ { \"noteType\": { \"tName\": \"DraftPunk\", \"sprite\": 1.0, \"spawnBeatOff\": -24.0, \"obj\": 12.0 }, \"noteTypeId\": 2.0, \"hasSpawned\": false, \"spawnBeatOff\": -24.0, \"row\": 4.0, \"beat\": 4.0 }, { \"noteType\": { \"tName\": \"DraftPunk\", \"sprite\": 1.0, \"spawnBeatOff\": -24.0, \"obj\": 12.0 }, \"noteTypeId\": 2.0, \"hasSpawned\": false, \"spawnBeatOff\": -24.0, \"row\": 2.0, \"beat\": 8.0 }, { \"noteType\": { \"tName\": \"DraftPunk\", \"sprite\": 1.0, \"spawnBeatOff\": -24.0, \"obj\": 12.0 }, \"noteTypeId\": 2.0, \"hasSpawned\": false, \"spawnBeatOff\": -24.0, \"row\": 6.0, \"beat\": 12.0 } ], \"sdBpm\": 108.0, \"sdFirstBeatOffset\": 0.0 } "
